{
 "title": "water",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Motor Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"test2\")\n  |> range(start: 2021-08-20T07:00:19.000Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tank\" and r[\"loc\"]==\"apartment1\" and r[\"_field\"]==\"water_in\" )\n  |> highestCurrent(n:1, groupColumns: [\"_time\"])\n  |> drop(columns: [\"_start\",\"_stop\",\"_field\",\"_measurement\",\"loc\"])\n  |> map(fn: (r) => ({ r with status:\n      if r._value == true then 1\n      else 0\n    }))\n    |> map(fn: (r) => ({ r with pow:\n      if r._value == true then \"7.5\"\n      else \"\"\n    }))\n  |> keep(columns:[\"status\",\"pow\",\"_time\"])"
    }
   ]
  },
  {
   "title": "water Present",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"test2\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tank\")\n  |> filter(fn: (r) => r[\"_field\"] == \"water_present\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"loc\"], valueColumn: \"_value\")\n  |> rename(fn : (column) =>  strings.title(v: column))"
    }
   ]
  },
  {
   "title": "water used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"test2\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tank\")\n  |> filter(fn: (r) => r[\"_field\"] == \"water_out\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"loc\"], valueColumn: \"_value\")\n  |> rename(fn : (column) =>  strings.title(v: column))"
    }
   ]
  },
  {
   "title": "Ø Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"test2\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\n  |> highestCurrent(n:2, groupColumns: [\"loc\"])\n  |> drop(columns: [\"_start\",\"_stop\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"loc\"], valueColumn: \"_value\")\n  |> rename(fn : (column) =>  strings.title(v: column))\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"test2\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pre\")\n  |> drop(columns: [\"_start\",\"_stop\",\"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"loc\"], valueColumn: \"_value\")\n  |> rename(fn : (column) =>  strings.title(v: column))\n"
    }
   ]
  },
  {
   "title": "weekly water consumption",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"test2\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tank\" and r[\"loc\"]==\"apartment1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"water_out\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> window(every: 1d)\n  |> sum(column:\"water_out\")\n  |> pivot(rowKey:[\"_measurement\"], columnKey: [\"_start\"], valueColumn: \"water_out\")\n  |> drop(columns:[\"loc\",\"_stop\",\"_measurement\",\"_time\",\"_field\",\"_value\",\"_start\"])\n  |> rename(fn : (column) =>  strings.title(v: strings.split(v: column, t: \"T\")[0] ))"
    }
   ]
  },
  {
   "title": "Ø Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"test2\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pre\")\n  |> highestCurrent(n:2, groupColumns: [\"loc\"])\n  |> drop(columns: [\"_start\",\"_stop\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"loc\"], valueColumn: \"_value\")\n  |> rename(fn : (column) =>  strings.title(v: column))\n"
    }
   ]
  },
  {
   "title": "Aparment 1 tank capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"test2\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tank\" and r[\"_field\"]==\"water_present\" and r[\"loc\"]==\"apartment1\")\n  |> highestCurrent(n:2, groupColumns: [\"loc\"])\n  |> drop(columns: [\"_start\",\"_stop\"])\n  |> keep(columns:[\"_value\"])\n  |> rename(fn : (column) =>  strings.title(v: column))"
    },
    {
     "query": "from(bucket: \"test2\")\n  |> range(start: 2021-08-20T07:00:19.000Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"const\" and r[\"loc\"]==\"apartment1\" and r[\"_field\"]==\"tank_capacity\" )\n  |> highestCurrent(n:1, groupColumns: [\"_time\"])\n  |> drop(columns: [\"_start\",\"_stop\",\"_field\",\"_measurement\",\"loc\"])\n  |> keep(columns:[\"_value\"])"
    },
    { "expression": "$A/$B*100", "type": "math" }
   ]
  },
  {
   "title": "Aparment 2 tank capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"test2\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tank\" and r[\"_field\"]==\"water_present\" and r[\"loc\"]==\"apartment2\")\n  |> highestCurrent(n:2, groupColumns: [\"loc\"])\n  |> drop(columns: [\"_start\",\"_stop\"])\n  |> keep(columns:[\"_value\"])\n  |> rename(fn : (column) =>  strings.title(v: column))"
    },
    {
     "query": "from(bucket: \"test2\")\n  |> range(start: 2021-08-20T07:00:19.000Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"const\" and r[\"loc\"]==\"apartment2\" and r[\"_field\"]==\"tank_capacity\" )\n  |> highestCurrent(n:1, groupColumns: [\"_time\"])\n  |> drop(columns: [\"_start\",\"_stop\",\"_field\",\"_measurement\",\"loc\"])\n  |> keep(columns:[\"_value\"])"
    },
    { "expression": "$A/$B*100", "type": "math" }
   ]
  }
 ]
}